# -*- coding: utf-8 -*-
"""Quantitative_Value_Investing_Strategy

Automatically generated by Colaboratory.
"""

!pip install -U pandas_datareader

import pandas_datareader as web
import pandas as pd
import numpy as np
import math
from scipy import stats

from google.colab import files
loaded_file = files.upload()

stocks = pd.read_csv('sp_500_stocks.csv')

stocks.head()

columns=['ticker','price','pe-ratio','shares2buy']

df = pd.DataFrame(columns=columns)

for stock in stocks['Ticker']:
  try:
    data = web.data.get_quote_yahoo(stock)
    df = df.append(
      pd.Series([
          stock,
          np.double(data['price']),
          np.double(data['trailingPE']),
          'N/A'
        ],
        index = columns
      ),
      ignore_index=True
    )
  except:
    pass

df

df.sort_values('pe-ratio', ascending=True, inplace=True)
df = df[df['pe-ratio'] > 0]
df = df[:50]

df.reset_index(drop=True, inplace=True)

df

portfolio_size = float(input('Enter the valueof your portfolio: '))

position_size = portfolio_size / len(df.index)

for i in range(len(df.index)):
  df.loc[i,'shares2buy'] = math.floor(position_size/df.loc[i,'price'])

df
